services:
  caddy:
    image: caddy:2.8
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - .caddy:/etc/caddy
  server:
    build:
      context: server
    restart: unless-stopped
    ports:
      - "8000:8000"
  client:
    build:
      context: client
    restart: unless-stopped
    ports:
      - "8000:8000"
