services:
  caddy:
    image: caddy:2.8
    restart: unless-stopped
    networks:
      - reverse_proxy
    cap_add:
      - NET_ADMIN
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - .caddy:/etc/caddy
  server:
    build:
      context: server
    restart: unless-stopped
    networks:
      - reverse_proxy
    ports:
      - 8000:8000
  client:
    build:
      context: client
    restart: unless-stopped
    networks:
      - reverse_proxy
    ports:
      - 5173:8000

networks:
  reverse_proxy:
    driver: "bridge"
    name: ${NETWORK_NAME:-reverse_proxy}
